<a href="https://colab.research.google.com/github/aa6910/BPhO-Computational-Challenge-2024/blob/main/2_2_intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to PyTorch as a replacement for Numpy / MATLAB

All the code in this course will be in the PyTorch library.  That's because PyTorch is widely agreed to be the best library for artificial intelligence/deep learning:
  * Most popular library in research
  * Battle-tested
  * Fantastic docs + tutorials + libraries than any other library
  * Pythonic and hackable: you can look at + modify the source for just about anything

PyTorch is many things.  But at its most basic, PyTorch is just a replacement for Numpy / MATLAB.  And that's how we're going to introduce PyTorch here!

Note the [PyTorch docs](https://pytorch.org/docs/stable/index.html) are great.  Learning your way around these will help alot!

Alternative libraries that are less popular but used by some people include JAX, Tensorflow, and Keras (often integrated with Tensorflow). Old dead libraries include Theano and Caffe.

In [1]:
#Lets start by importing PyTorch
import torch as t

# Initializing PyTorch Tensors

In PyTorch, a Tensor is a container for numbers.

Weirdly, a Tensor could be a scalar/vector/matrix / N-dimensional array etc...

In [ ]:
#We can make a scalar one using,
scalar = t.tensor(1.)
print(f"Scalar type: {type(scalar)}")
print("Scalar value:")
print(scalar)
print()
#We can make a length 3 vector of ones using,
vector = t.ones(3)
print(f"Vector type: {type(vector)}")
print("Vector value:")
print(vector)
print()

#We can make a 3x3 matrix of zeros using,
matrix = t.zeros(3,3)
print(f"Matrix type: {type(matrix)}")
print("Matrix value:")
print(matrix)
print()

#We can make a 3x3x3 tensor of zeros (think of a cube of 0s, or a list of 3 3x3 matrices of zeros) using,
threeDtensor = t.zeros(3,3,3)
print(f"3D Tensor type: {type(threeDtensor)}")
print("3D Tensor value:")
print(threeDtensor)

#... and so on. Tensors can have as many dimensions as you want.


Scalar type: <class 'torch.Tensor'>
Scalar value:
tensor(1.)

Vector type: <class 'torch.Tensor'>
Vector value:
tensor([1., 1., 1.])

Matrix type: <class 'torch.Tensor'>
Matrix value:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

3D Tensor type: <class 'torch.Tensor'>
3D Tensor value:
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
#There are loads of commands in pytorch for creating tensors, including
a = t.arange(7) # 0 to n-1 (length n)
print(a)
b = t.linspace(0, 1, 4) # start, end, num-points
print(b)
c = t.eye(4) #Identity matrix
print(c)
d = t.diag(t.tensor([1, 2, 3, 4]))
print(d)
e = t.rand(4) # uniform in [0, 1]
print(e)
f = t.randn(4) # draw from Gaussian
print(f)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0.0000, 0.3333, 0.6667, 1.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])
tensor([0.7215, 0.7387, 0.5770, 0.2103])
tensor([-0.6559, -0.4564, -0.0083, -0.7566])


In [ ]:
#You can do all the usual arithmetic operations (elementwise) on this tensor,
a = t.arange(4)
print(a+1)
print(5*a)
print(a/2)
print(a+a)

tensor([1, 2, 3, 4])
tensor([ 0,  5, 10, 15])
tensor([0.0000, 0.5000, 1.0000, 1.5000])
tensor([0, 2, 4, 6])


# Tensor shape

90% of understanding and manipulating PyTorch Tensors comes down to understand tensor _shape_.

In [ ]:
#To get the shape, use tensor.shape (scalar, vector, matrix, and threeDtensor and  are defined above)
print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print(threeDtensor.shape)

torch.Size([])
torch.Size([3])
torch.Size([3, 3])
torch.Size([3, 3, 3])


In [ ]:
#You can use these shapes to get a new Tensor of the same shape
zero_vector = t.zeros(vector.shape)
print(zero_vector)

tensor([0., 0., 0.])


In [ ]:
#A tensor containing a single scalar could have any number of shapes / dimensions:
print(t.zeros(()).shape)  #A real scalar
print(t.zeros(1).shape)   #A length-1 vector
print(t.zeros(1,1).shape) #A 1x1 matrix
print(t.zeros(1,1,1).shape)#A 1x1x1 tensor
#... and so on

#You should prefer the first one unless you have good reason not to.

torch.Size([])
torch.Size([1])
torch.Size([1, 1])
torch.Size([1, 1, 1])


In [ ]:
#A vector could (without complicating things horrendously) have three different shapes:
print(t.zeros(3))   #A vector (could be interpreted as row or column, depending on context)
print(t.zeros(3,1)) #A column-vector, represented as a 3x1 matrix
print(t.zeros(1,3)) #A row-vector,    represented as a 1x3 matrix

tensor([0., 0., 0.])
tensor([[0.],
        [0.],
        [0.]])
tensor([[0., 0., 0.]])


## Tensor broadcasting

Sometimes you want to e.g. add a matrix to a vector (adding the vector to each of the matrix, perhaps). When we try to add / multiply / whatever two tensors with different shapes, Pytorch will attempt to automatically "broadcast" one tensor across the other. Broadcasting can get tricky, but it is very useful, as code written using broadcasting will run much faster than doing the same operation using python for-loops.

In [ ]:
#You can do this, which will add the vector y to each row of X
X = t.ones(3,4)
y = t.randn(4)
print(X)
print(y)
print(X+y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([-1.4321,  0.2741, -0.7210, -1.2223])
tensor([[-0.4321,  1.2741,  0.2790, -0.2223],
        [-0.4321,  1.2741,  0.2790, -0.2223],
        [-0.4321,  1.2741,  0.2790, -0.2223]])


In [ ]:
#But you can't do this:
X = t.ones(3,4)
y = t.rand(3)
print(X+y)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

To understand what works / doesn't, we need to understand the **broadcasting rules**!

From the [Pytorch documentation](https://pytorch.org/docs/stable/notes/broadcasting.html):

*Two tensors are “broadcastable” if the following rules hold:*
- *Each tensor has at least one dimension.*
- *When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.*

Let's try and understand these in code.

In [ ]:
#Key rule: dimensions must match, or be 1:
X = t.ones(2,3,4)
Y = t.rand(1,3,1)
#Here, the middle dimensions match.
#The first dimensions are 2 (for X) and 1 (for Y), so the Y-dimension broadcasts
#The third dimensions are 4 (for X) and 1 (for Y), so again, the Y-dimension broadcasts.
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


This translates into maths as:
\begin{align}
  Z_{ijk} = X_{ijk} + Y_j
\end{align}

Note that we only have dimension size $1$ for $Y$ in the $i$ and $k$ dimensions, so it's as if those indices don't exist on the Y tensor.

In other words, since the $j$ dimensions of $X$ and $Y$ match, and $Y$ only has size 1 in dimensions $i$ and $k$, then we can add the $j$ dimensions together for all $i$ and for all $k$. If $X$, which is of size $(2,3,4)$, were viewed as a list of 2 matrices of size $3 \times 4$, then we're adding the vector $Y$ of length 3 to every column of every matrix in $X$ (since each column of each matrix is a vector of length 3, this makes sense).

Without broadcasting, we'd need to write a python for-loop to achieve something like this, which, for very big tensors, will be very slow. Broadcasting uses fast C code, and is therefore much quicker.

What happens if the tensors have different numbers of dimensions?

In [ ]:
#Here, X is a 3-dimensional tensor, while Y is a 1-dimensional tensor,
X = t.ones(2,3,4)
Y = t.ones(4)
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


This expression translates to math as,
\begin{align}
  Z_{ijk} = X_{ijk} + Y_k.
\end{align}
There are two ways to think about this:
* PyTorch matches dimensions from right to left,
* PyTorch fills the "missing" dimensions on the left with ones.  In which case, the following code is equivalent,

In [ ]:
#The above code works is equivalent to this
X = t.ones(2,3,4)
Y = t.ones(1,1,4)
Z = X+Y
print(Z.shape)

torch.Size([2, 3, 4])


However, the following code gives an error, because `X.shape = torch.Size([2])` behaves like `Y.shape = torch.Size([1,1,2])`, and this doesn't broadcast with `X.shape = torch.Size(2,3,4)`, because in the third dimesion, $2 \neq 4$.

In [ ]:
# This code gives an error
X = t.ones(2,3,4)
Y = t.rand(2)
X+Y

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

This expression translates to math in the same way, as
\begin{align}
  Z_{ijk} = X_{ijk} + Y_k.
\end{align}
But now the $k$ dimension on X (size 4) and the $k$ dimension on Y (size 2) don't match, which gives an error.

In [ ]:
#The above code behaves just like, and therefore gives us an error
X = t.ones(2,3,4)
Y = t.rand(1,1,2)
X+Y

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

But what if we do want to do broadcast along the first dimension?  We need to construct $Y$ so that the length 2 dimension appears in the right place!

In [ ]:
# Manually inserting ones so we can sum the first dimensions of X and y together
X = t.ones(2,3,4)
Y = t.randn(2,1,1)
Z = X+Y
print(X)
print(Y)
print(Z)
print(Z.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[ 1.1794]],

        [[-0.7046]]])
tensor([[[2.1794, 2.1794, 2.1794, 2.1794],
         [2.1794, 2.1794, 2.1794, 2.1794],
         [2.1794, 2.1794, 2.1794, 2.1794]],

        [[0.2954, 0.2954, 0.2954, 0.2954],
         [0.2954, 0.2954, 0.2954, 0.2954],
         [0.2954, 0.2954, 0.2954, 0.2954]]])
torch.Size([2, 3, 4])


This expression translates to math as
\begin{align}
  Z_{ijk} = X_{ijk} + Y_i.
\end{align}
So now the "i" dimension on X and the "i" dimension on Y do match! From the output of the above code, we can see this is like $X$ being 2 matrices of size $3 \times 4$, and we add the first element of $Y$ to the first matrix, and the second element of $Y$ to the second matrix.

But what if we already have a tensor Y, but it's the wrong shape (doesn't have the extra 1s needed)?

In [ ]:
X = t.ones(2,3,4)
Y = t.randn(2)
#Y is the wrong shape to broadcast with X!
print(Y.shape) #torch.Size([2])
# and so X+Y gives an error:
X+Y


torch.Size([2])


RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

We can add extra dimensions to Y using `Y[:, None, None]` (this is special Pytorch notation, don't attach any significance to the word "None" here)

In [ ]:
Y = Y[:, None, None]
#The None's add extra 1 dimensions, we have a tensor of the right shape!
print(Y.shape) #torch.Size([2,1,1])
#And the broadcasting works,
print(X+Y)

torch.Size([2, 1, 1])
tensor([[[1.2383, 1.2383, 1.2383, 1.2383],
         [1.2383, 1.2383, 1.2383, 1.2383],
         [1.2383, 1.2383, 1.2383, 1.2383]],

        [[0.5342, 0.5342, 0.5342, 0.5342],
         [0.5342, 0.5342, 0.5342, 0.5342],
         [0.5342, 0.5342, 0.5342, 0.5342]]])


# Additional useful operations

In [ ]:
#Matrix operations
A = t.randn((2,3))
print("Matrix")
print(A)
print("\nMatrix Transpose")
print(A.mT)
print("\nElementwise product")
print(A * A)
print("\nMatrix Product")
print(A @ A.mT)

Matrix
tensor([[-0.2524, -0.1976,  1.3742],
        [ 1.6297, -0.9678, -1.9343]])

Matrix Transpose
tensor([[-0.2524,  1.6297],
        [-0.1976, -0.9678],
        [ 1.3742, -1.9343]])

Elementwise product
tensor([[0.0637, 0.0390, 1.8885],
        [2.6558, 0.9366, 3.7416]])

Matrix Product
tensor([[ 1.9912, -2.8783],
        [-2.8783,  7.3340]])


In [ ]:
#Matrix-vector operations
N = 2
M = 3
A = t.randn((M, N))
a_vec = t.randn(M)
b_vec = t.randn(N)

#Interprets a_vec as a row-vector (otherwise matrix-vector product wouldn't make sense)
#Input is a vector (with one dimension); output is a vector (with one dimension)
print((a_vec @ A).shape)
#Interprets b_vec as a column-vector (otherwise matrix-vector product wouldn't make sense)
#Input is a vector (with one dimension); output is a vector (with one dimension)
print((A @ b_vec).shape)
#We can also convert a_vec to an explicit row-vector, by converting to a matrix
#of shape 1xM
a_rowvec = a_vec[None, :]
print(a_rowvec)
#Now, input is a row-vector in matrix form (1xM), so output is a row-vector in matrix form (1xN)
print((a_rowvec @ A).shape)
#Likewise, we can convert b_vec to an explicit column-vector, by converting to a matrix
#of shape Nx1
b_colvec = b_vec[:, None]
print(b_colvec)
#Now, input is a row-vector in matrix form (Nx1), so output is a row-vector in matrix form (Mx1)
print((A @ b_colvec).shape)



torch.Size([2])
torch.Size([3])
tensor([[ 1.2353, -1.0726, -0.5326]])
torch.Size([1, 2])
tensor([[1.9616],
        [0.5453]])
torch.Size([3, 1])


In [ ]:
#One-argument operations.  Note that for most (but not all) of these operations,
#there are two ways of calling:
#1. There is a function that lives in the torch package.  As we have imported torch
#  as `t`, these are e.g. t.exp().
#2. Alternatively, they can be called as methods on the tensor, like x.log():
x = t.rand(3)
print("Exponential")
print(t.exp(x))
print(x.exp())
print("\n(Natural) Logarithm")
print(t.log(x))
print(x.log())
print("\nExponential")
print(t.exp(x))
print(x.exp())
print("\nSine")
print(t.sin(x))
print(x.sin())
print("\nCosine")
print(t.cos(x))
print(x.cos())
#For _loads_ more, see https://pytorch.org/docs/stable/torch.html

Exponential
tensor([2.2252, 1.0348, 1.2442])
tensor([2.2252, 1.0348, 1.2442])

(Natural) Logarithm
tensor([-0.2233, -3.3742, -1.5209])
tensor([-0.2233, -3.3742, -1.5209])

Exponential
tensor([2.2252, 1.0348, 1.2442])
tensor([2.2252, 1.0348, 1.2442])

Sine
tensor([0.7173, 0.0342, 0.2168])
tensor([0.7173, 0.0342, 0.2168])

Cosine
tensor([0.6968, 0.9994, 0.9762])
tensor([0.6968, 0.9994, 0.9762])


##Reduction operations

There are a bunch of operations (mean, sum, prod, std, var) etc.
They all do the obvious things.
But the key trick is understanding how these operations interact with Tensor shape.

In [ ]:
A = t.randn(2,3,4)

In [ ]:
#All these ops reduce over a dimension, and we need to provide an explicit index for that dimension.
print(A.mean(0).shape)
print(A.mean(1).shape)
print(A.mean(2).shape)
#We can index from the back, as in list/tuple indexing
print(A.mean(-1).shape) # In this case, this is equivalent to A.mean(2) because 2 is the last dimension (dimensions are zero indexed, 0,1,2)

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])
torch.Size([2, 3])


`A.mean(0)` translates to math as:
\begin{align}
M_{jk} = \tfrac{1}{2} \sum_{i=1}^2 A_{ijk}
\end{align}
`A.mean(1)` translates to math as:
\begin{align}
M_{ik} = \tfrac{1}{3} \sum_{j=1}^3 A_{ijk}
\end{align}
`A.mean(2)` translates to math as:
\begin{align}
M_{ij} = \tfrac{1}{4} \sum_{k=1}^4 A_{ijk}
\end{align}

What if we want to mean-subtract $A$?  That's easy if we want to take the mean over the first dimension, as the shapes broadcast:

In [ ]:
# A and A_mean follow the broadcasting rules in this case
A_mean = A.mean(0)
print(f"A.shape =   {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =   torch.Size([2, 3, 4])
A_mean.shape = torch.Size([3, 4])


tensor([[[ 0.2094, -0.0560,  0.7336,  1.4648],
         [-0.9604,  0.6742, -1.0661, -0.0193],
         [ 0.7797, -0.2690, -1.2200,  0.7792]],

        [[-0.2094,  0.0560, -0.7336, -1.4648],
         [ 0.9604, -0.6742,  1.0661,  0.0193],
         [-0.7797,  0.2690,  1.2200, -0.7792]]])

But mean-subtracting $A$ doesn't automatically work if we want to take the mean over the second or third dimension, as the resulting mean Tensor doesn't broadcast with $A$.

In [ ]:
# A and A_mean don't follow the broadcasting rules in this case, so will throw an error
A_mean = A.mean(2)
print(f"A.shape =   {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =   torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3])


RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

We could fix this using `None` to add the extra 1 back in:

In [ ]:
# Using None to add 1s back in will work
A_mean = A.mean(2)[:, :, None]
print(f"A.shape =   {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean


A.shape =   torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3, 1])


tensor([[[-0.0262, -0.6963,  0.1749,  0.5477],
         [-1.4964,  1.5260, -1.2426,  1.2129],
         [ 0.6108,  0.0215, -1.3796,  0.7473]],

        [[ 0.7308,  0.5915, -0.1164, -1.2059],
         [-0.2614, -0.5081,  0.2037,  0.5658],
         [-0.9137,  0.5945,  1.0954, -0.7762]]])

But this is tedious, requiring us to make sure we put `None` in the correct place that we took the mean over. Looking at [the docs](https://pytorch.org/docs/stable/generated/torch.mean.html), there's an easy way to fix this bug: use the `keepdim=True` kwarg!
This keeps a single element in the final dimension, so broadcasting still works!

In [ ]:
# Using the keepdim=True kwarg makes thing simpler.
A_mean = A.mean(2, keepdim=True)
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A-A_mean

A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3, 1])


tensor([[[-0.0262, -0.6963,  0.1749,  0.5477],
         [-1.4964,  1.5260, -1.2426,  1.2129],
         [ 0.6108,  0.0215, -1.3796,  0.7473]],

        [[ 0.7308,  0.5915, -0.1164, -1.2059],
         [-0.2614, -0.5081,  0.2037,  0.5658],
         [-0.9137,  0.5945,  1.0954, -0.7762]]])

# Exercises
## 1)
(a): Define a tensor A that contains the sequence of integers 20,...,139 inclusive (so 120 elements in total)

In [4]:
A = t.tensor(range(20,140))

In [10]:
#@title Solution for (a): (click `Show code` to expand)

A = t.arange(20,140)
print(f"A shape: {A.shape}")

A shape: torch.Size([120])


(b) Reshape the tensor to have shape `(2,3,20)`

In [7]:
A = t.reshape(A,(2,3,20))

In [11]:
#@title Solution for (b)
A = A.reshape(2,3,20)
print(f"A shape: {A.shape}")

A shape: torch.Size([2, 3, 20])


(c) Multiply the following matrix `B` with shape `(2,3)` with `A` using broadcasting, matching the first and second dimensions of `A` and `B` to obtain a new tensor `C`. `A` can be viewed as 2 matrices of size $3 \times 20$. In words, what calculations have we done to obtain `C`? (in terms of the matrices / rows / columns of `A` and `B`).

In [16]:
B = t.tensor([[1,2,3],[4,5,6]])
# A is implicitly the tensor from the previous exercise (shape (2,3,20))
C = A * B[:,:,None]

# YOUR EXPLANATION HERE:

In [ ]:
#@title Solution for (c)
B = t.tensor([[1,2,3],[4,5,6]])
C = A * B[:,:,None]

# Explanation in words: For the first matrix in A, we have multiplied each column by the first row of B. For the second matrix in A, we have multiplied each column by the second row of B.

print(f"C: {C}")

C: tensor([[[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106,
          108, 110, 112, 114, 116, 118],
         [180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219,
          222, 225, 228, 231, 234, 237]],

        [[320, 324, 328, 332, 336, 340, 344, 348, 352, 356, 360, 364, 368, 372,
          376, 380, 384, 388, 392, 396],
         [500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555, 560, 565,
          570, 575, 580, 585, 590, 595],
         [720, 726, 732, 738, 744, 750, 756, 762, 768, 774, 780, 786, 792, 798,
          804, 810, 816, 822, 828, 834]]])


(d) Implement the following formula applied to `C` using Pytorch functions. Give your answer as a "scalar tensor", i.e. a tensor with no redundant size 1 dimensions (pytorch will return `torch.Size([])` for `d.shape` if it is a true scalar. You might like to use the `torch.squeeze()` function, though you don't have to). Your answer should be 9.573 to the nearest 3 decimal places:
$$d = \frac{1}{2} \sum_{i} \sum_k  \left[\text{sin}\left(\sum_j C_{ijk} \right)\right]^2$$

In [22]:
d = 0.5 * C.sum(1, keepdim=True).sin().pow(2).sum(0, keepdim=True).sum(2, keepdim=True).squeeze()
print(d)

tensor([[1.4962, 0.8988, 0.5071, 1.4887, 1.1738, 0.3639, 1.2688, 1.4403, 0.4433,
         0.9721, 1.5160, 0.6678, 0.8040, 1.4131, 0.8324, 0.8143, 1.3163, 0.8363,
         0.8509, 1.3650],
        [1.3660, 0.8853, 0.7799, 1.4059, 0.6878, 1.0016, 1.3128, 0.5855, 1.2330,
         1.1073, 0.6272, 1.3819, 0.8700, 0.7921, 1.3984, 0.6886, 1.0095, 1.2961,
         0.6073, 1.2133],
        [1.3884, 1.2820, 1.1434, 1.0022, 0.8853, 0.8101, 0.7804, 0.7870, 0.8119,
         0.8352, 0.8424, 0.8292, 0.8034, 0.7820, 0.7851, 0.8286, 0.9179, 1.0448,
         1.1883, 1.3200]])


In [ ]:
#@title Solution for (d):

# This first method uses keepdim=True to make sure the shape stays the same throughout, which can sometimes help avoid mistakes.
# .squeeze() at the end will remove all dimensions with size 1 (i.e. the opposite of [:,None] notation)
d = C.sum(1,keepdim=True).sin().pow(2).sum(2, keepdim=True).mean(0, keepdim=True).squeeze()

# This second method eschews the keepdim=True kwargs, instead letting the methods collapse the dimension each time.
# This requires care because the indices of remaining dimensions can change when collapsing dimensions.
# But as you can see, it is much shorter and cleaner.
d_alt = C.sum(1).sin().pow(2).sum(1).mean()

# We can also use the functions in their t.sum(C, 1) form (pytorch function) rather than C.sum(1) form (tensor method).
# Notice this method starts "outside in" whilst the other method starts "inside out"
d_func = t.mean(t.sum(t.pow(t.sin(t.sum(C,1)),2),1))

# There are many ways to write the same thing in Pytorch! Find the way that suits you best.

assert(d == d_alt)
assert(d_alt == d_func)

print(f"d: {d}")
print(f"d.shape: {d.shape}")
# print(f"d_alt: {d_alt}")
# print(f"d_alt.shape: {d_alt.shape}")
# print(f"d_func: {d_func}")
# print(f"d_func.shape: {d_func.shape}")

d: 9.573009490966797
d.shape: torch.Size([])
